services:
  postgres-subscription:
    image: postgres:16-alpine
    ports:
      - 1401:5432
    volumes:
      - uservice_subscription_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  uservice_subscription_postgres:
